#!/usr/bin/env node
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

// Convert import.meta.url to __dirname equivalent
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --- Configuration ---
const appName = "Auth0 Picture Matching Game Final App"; // Slightly different name for clarity
const appPort = 3000;
const callbackUrl = `http://localhost:${appPort}`;
const envFilePath = path.join(__dirname, "..", ".env.local"); // Path to final-app/.env.local

function runCommand(command) {
  try {
    console.log(`› ${command}`);
    return execSync(command, { stdio: "pipe" }).toString().trim();
  } catch (error) {
    console.error(`Error executing command: ${command}`);
    if (error.stderr) {
      console.error(error.stderr.toString());
    }
    process.exit(1);
  }
}

function runInteractiveCommand(command) {
  try {
    console.log(`› ${command}`);
    execSync(command, { stdio: "inherit" });
  } catch (error) {
    console.error(`Error executing command: ${command}`);
    process.exit(1);
  }
}

async function main() {
  console.log("🚀 Starting Auth0 Application Setup for FINAL APP...");

  // 1. Check if Auth0 CLI is installed
  try {
    runCommand("auth0 --version");
    console.log("Auth0 CLI found.");
  } catch (e) {
    console.error(
      "Error: Auth0 CLI not found. Please ensure it's installed and in your PATH."
    );
    console.error(
      "In Codespaces, this should be handled by the devcontainer.json feature."
    );
    process.exit(1);
  }

  // 2. Login (skip if already authenticated)
  console.log("\nStep 1: Authenticating with Auth0...");
  try {
    runCommand("auth0 tenants list");
    console.log("Already authenticated with Auth0.");
  } catch {
    console.log("Not logged in. Opening browser for authentication...");
    console.log(
      "Please ensure you log in to the Auth0 tenant you wish to use for this workshop."
    );
    runInteractiveCommand("auth0 login");
    console.log("✅ Authentication successful!");
  }

  // 3. Create the Application
  console.log(`\nStep 2: Creating the '${appName}' application...`);
  const appCreateOutput = runCommand(
    `auth0 apps create --name "${appName}" --type regular --description "Completed workshop app for the picture matching game" --json --no-input`
  );
  const appData = JSON.parse(appCreateOutput);
  const clientId = appData.client_id;
  const clientSecret = appData.client_secret;
  console.log(`✅ Application created with Client ID: ${clientId}`);

  // 4. Configure URLs
  console.log("\nStep 3: Configuring application URLs...");
  runCommand(
    `auth0 apps update ${clientId} --callbacks "${callbackUrl}" --logout-urls "${callbackUrl}" --web-origins "${callbackUrl}"`
  );
  console.log("✅ URLs configured successfully.");

  // 5. Get Auth0 Tenant Domain
  console.log("\nStep 4: Retrieving Auth0 Tenant Domain...");
  const tenantDomain = runCommand("auth0 tenants domain");
  const issuerBaseUrl = `https://${tenantDomain}/`;
  console.log(`✅ Auth0 Tenant Domain: ${tenantDomain}`);

  // 6. Generate a secure secret for the Next.js app
  console.log("\nStep 5: Generating a secure Auth0 Secret...");
  const auth0Secret = runCommand("openssl rand -hex 32");
  console.log("✅ Auth0 Secret generated.");

  // 7. Update the .env.local file
  console.log(`\nStep 6: Updating your ${envFilePath} file...`);

  // Read existing .env.local if it exists to preserve Google credentials
  let existingEnvContent = "";
  if (fs.existsSync(envFilePath)) {
    existingEnvContent = fs.readFileSync(envFilePath, "utf-8");
  }

  // Preserve existing GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
  let googleClientId = "";
  let googleClientSecret = "";
  const googleClientIdMatch = existingEnvContent.match(
    /^GOOGLE_CLIENT_ID=(.*)$/m
  );
  const googleClientSecretMatch = existingEnvContent.match(
    /^GOOGLE_CLIENT_SECRET=(.*)$/m
  );
  if (googleClientIdMatch && googleClientIdMatch[1]) {
    googleClientId = googleClientIdMatch[1];
  }
  if (googleClientSecretMatch && googleClientSecretMatch[1]) {
    googleClientSecret = googleClientSecretMatch[1];
  }

  const envContent = `
# Auth0 Credentials (auto-generated by setup-auth0.mjs)
AUTH0_SECRET='${auth0Secret}'
AUTH0_BASE_URL='${callbackUrl}'
AUTH0_ISSUER_BASE_URL='${issuerBaseUrl}'
AUTH0_CLIENT_ID='${clientId}'
AUTH0_CLIENT_SECRET='${clientSecret}'

# Google Credentials (provided via Codespaces secrets)
GOOGLE_CLIENT_ID=${googleClientId || process.env.GOOGLE_CLIENT_ID || ""}
GOOGLE_CLIENT_SECRET=${googleClientSecret || process.env.GOOGLE_CLIENT_SECRET || ""}
  `;

  fs.writeFileSync(envFilePath, envContent.trim());
  console.log(`✅ ${envFilePath} has been configured!`);

  console.log(
    "\n🎉 All done! Your Auth0 application (final version) is ready."
  );
  console.log(
    "You can now run 'pnpm run dev:final' from the root directory to start the game."
  );
}

main();
