#!/usr/bin/env node
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const appName = "Workshop Email Collector";
const devVarsPath = path.join(__dirname, "..", ".dev.vars");

function runCommand(command) {
  try {
    console.log(`› ${command}`);
    return execSync(command, { stdio: "pipe" }).toString().trim();
  } catch (error) {
    console.error(`Error executing command: ${command}`);
    if (error.stderr) {
      console.error(error.stderr.toString());
    }
    process.exit(1);
  }
}

function parseJsonOutput(output) {
  const jsonStart = output.indexOf("{");
  if (jsonStart !== -1) {
    return JSON.parse(output.slice(jsonStart));
  }
  const arrayStart = output.indexOf("[");
  if (arrayStart !== -1) {
    return JSON.parse(output.slice(arrayStart));
  }
  throw new Error("No JSON found in output");
}

function runInteractiveCommand(command) {
  try {
    console.log(`› ${command}`);
    execSync(command, { stdio: "inherit" });
  } catch (error) {
    console.error(`Error executing command: ${command}`);
    process.exit(1);
  }
}

function ask(question, defaultValue) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    const prompt = defaultValue
      ? `${question} (${defaultValue}): `
      : `${question}: `;
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

async function main() {
  console.log("🚀 Starting Auth0 Setup for Email Collector...\n");

  // 1. Check if Auth0 CLI is installed
  try {
    runCommand("auth0 --version");
    console.log("Auth0 CLI found.\n");
  } catch {
    console.error(
      "Error: Auth0 CLI not found. Please install it: https://github.com/auth0/auth0-cli"
    );
    process.exit(1);
  }

  // 2. Login (skip if already authenticated)
  console.log("Step 1: Authenticating with Auth0...");
  try {
    runCommand("auth0 tenants list");
    console.log("Already authenticated with Auth0.\n");
  } catch {
    console.log("Not logged in. Opening browser for authentication...");
    runInteractiveCommand("auth0 login");
    console.log("✅ Authentication successful!\n");
  }

  // 3. Ask for the Worker URL
  const workerUrl = await ask(
    "Step 2: Enter your deployed Worker URL",
    "http://localhost:8787"
  );
  console.log(`Using URL: ${workerUrl}\n`);

  // 4. Create a Regular Web Application
  console.log(`Step 3: Creating the '${appName}' application...`);
  const appCreateOutput = runCommand(
    `auth0 apps create --name "${appName}" --type regular --description "Collects participant Gmail addresses for workshop Google OAuth test users" --json --no-input`
  );
  const appData = parseJsonOutput(appCreateOutput);
  const clientId = appData.client_id;
  const clientSecret = appData.client_secret;
  console.log(`✅ Application created with Client ID: ${clientId}\n`);

  // 5. Configure URLs
  console.log("Step 4: Configuring application URLs...");
  runCommand(
    `auth0 apps update ${clientId} --callbacks "${workerUrl}/callback" --logout-urls "${workerUrl}" --web-origins "${workerUrl}"`
  );
  console.log("✅ URLs configured successfully.\n");

  // 6. Get tenant domain
  console.log("Step 5: Retrieving Auth0 Tenant Domain...");
  const tenantsOutput = runCommand("auth0 tenants list --json");
  const tenants = parseJsonOutput(tenantsOutput);
  const activeTenant = tenants.find((t) => t.active);
  if (!activeTenant) {
    console.error("No active Auth0 tenant found. Run 'auth0 tenants use <tenant>' first.");
    process.exit(1);
  }
  const tenantDomain = activeTenant.name;
  console.log(`✅ Auth0 Tenant Domain: ${tenantDomain}\n`);

  // 7. Generate cookie secret
  console.log("Step 6: Generating a secure cookie secret...");
  const cookieSecret = runCommand("openssl rand -hex 32");
  console.log("✅ Cookie secret generated.\n");

  // 8. Write .dev.vars file
  console.log(`Step 7: Writing ${devVarsPath}...`);
  const devVarsContent = `# Auth0 Credentials (auto-generated by setup-auth0.mjs)
AUTH0_DOMAIN=${tenantDomain}
AUTH0_CLIENT_ID=${clientId}
AUTH0_CLIENT_SECRET=${clientSecret}
COOKIE_SECRET=${cookieSecret}
`;
  fs.writeFileSync(devVarsPath, devVarsContent);
  console.log(`✅ ${devVarsPath} has been configured!\n`);

  // 9. Print next steps
  console.log("🎉 Auth0 setup complete!\n");
  console.log("For local development:");
  console.log("  pnpm dev:emails\n");
  console.log("For production deployment:");
  console.log("  1. Deploy the worker: pnpm deploy:emails");
  console.log("  2. Set production secrets:");
  console.log(
    `     cd email-collector && npx wrangler secret put AUTH0_CLIENT_SECRET`
  );
  console.log(`     cd email-collector && npx wrangler secret put COOKIE_SECRET`);
  console.log(
    `  3. Update Auth0 app callback URLs to your production Worker URL`
  );
  console.log(
    `     auth0 apps update ${clientId} --callbacks "<PROD_URL>/callback" --logout-urls "<PROD_URL>" --web-origins "<PROD_URL>"`
  );
}

main();
